### BEDROOM
- platform: mqtt
  name: "Bedroom Light"
  command_topic: "cmnd/sonoff3/power"
  state_topic: "stat/sonoff3/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1

### OFFICE
- platform: mqtt
  name: "Office Light"
  command_topic: "cmnd/sonoff5/power"
  state_topic: "stat/sonoff5/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1
- platform: mqtt
  name: "Office Lamp"
  command_topic: "cmnd/sonoff6/power"
  state_topic: "stat/sonoff6/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1

### COMMON AREAS
- platform: mqtt
  name: "Family Light"
  command_topic: "cmnd/sonoff2/power"
  state_topic: "stat/sonoff2/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1
- platform: mqtt
  name: "Dining Room"
  command_topic: "cmnd/sonoff9/power"
  state_topic: "stat/sonoff9/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1
- platform: mqtt
  name: "Kitchen Light"
  command_topic: "cmnd/sonoff11/power"
  state_topic: "stat/sonoff11/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1
- platform: mqtt
  name: "Parlor Light"
  command_topic: "cmnd/sonoff14/power"
  state_topic: "stat/sonoff14/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1

### OUTSIDE
- platform: mqtt
  name: "Landscape"
  command_topic: "cmnd/sonoff10/power"
  state_topic: "stat/sonoff10/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1
- platform: mqtt
  name: "Party"
  command_topic: "cmnd/sonoff7/power"
  state_topic: "stat/sonoff7/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1

### TEMP
- platform: mqtt
  name: "Christmas Tree"
  command_topic: "cmnd/sonoff13/power"
  state_topic: "stat/sonoff13/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1

- platform: mqtt
  name: "Christmas Outside"
  command_topic: "cmnd/sonoff15/power"
  state_topic: "stat/sonoff15/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 1

### sat1
- platform: mqtt
  name: "sat1_0"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "0,1"
  payload_off: "0,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_1"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "1,1"
  payload_off: "1,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_2"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "2,1"
  payload_off: "2,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_3"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "3,1"
  payload_off: "3,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_4"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "4,1"
  payload_off: "4,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_5"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "5,1"
  payload_off: "5,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_6"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "6,1"
  payload_off: "6,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_10"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "10,1"
  payload_off: "10,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_11"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "11,1"
  payload_off: "11,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_15"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "15,1"
  payload_off: "15,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_16"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "16,1"
  payload_off: "16,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_27"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "27,1"
  payload_off: "27,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_28"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "28,1"
  payload_off: "28,0"
  retain: true
  qos: 1
- platform: mqtt
  name: "sat1_29"
  command_topic: "relays/sat1"
  state_topic: "relays/sat1"
  payload_on: "29,1"
  payload_off: "29,0"
  retain: true
  qos: 1
