- alias: Button - Office Light On
  trigger:
    platform: mqtt
    topic: "switches/office0"
    payload: "PUSH"
  condition:
    - condition: state
      entity_id: light.office_light
      state: "off"
  action:
    service: homeassistant.turn_on
    entity_id: light.office_light

- alias: Button - Office Light Off
  trigger:
    platform: mqtt
    topic: "switches/office0"
    payload: "PUSH"
  condition:
    - condition: state
      entity_id: light.office_light
      state: "on"
  action:
    service: homeassistant.turn_off
    entity_id: light.office_light

- alias: Button - Office Lamp On
  trigger:
    platform: mqtt
    topic: "switches/office3"
    payload: "PUSH"
  condition:
    - condition: state
      entity_id: light.office_lamp
      state: "off"
  action:
    service: homeassistant.turn_on
    entity_id: light.office_lamp

- alias: Button - Office Lamp Off
  trigger:
    platform: mqtt
    topic: "switches/office3"
    payload: "PUSH"
  condition:
    - condition: state
      entity_id: light.office_lamp
      state: "on"
  action:
    service: homeassistant.turn_off
    entity_id: light.office_lamp

